language: cpp

matrix:
  include:
    - os: linux
      dist: xenial
      compiler:
        - clang++
        - gcc
    - os: osx
      osx_image: xcode10.1
      compiler: clang

# use travis-ci docker based infrastructure
sudo: false

addons:
  apt:
    sources:
      - kubuntu-backports
      - ubuntu-toolchain-r-test
      - llvm-toolchain-precise-3.6
    packages:
      - libclang-3.6-dev
      - llvm-3.6-dev
      - clang-3.6
      - gcc-6
      - g++-6
      - cmake
      # - libgtest-dev # get it from the Git repository
      - gdb
      - texlive-extra-utils
      - texlive-fonts-extra
      - texlive-latex-recommended
      - latex-xcolor

env:
  global:
  #- CPPAD_HOME=`pwd`/cppadcg_deps/cppad/install/include
  #- CPPAD_HOME=`pwd`/cppadcg_deps/CppAD-20170000.8/install/include
  #- EIGEN_HOME=`pwd`/cppadcg_deps/eigen-eigen-5a0156e40feb/install/include

before_install:
  - if [ "$CXX" == "g++" ]; then export CC="$(which gcc-6)" CXX="$(which g++-6)"; fi
  # - if [ "$CXX" == "clang++" ]; then export CC="$(which clang-3.8)" CXX="$(which clang++-3.8)"; fi

install:
  - mkdir cppadcg_deps
  - cd cppadcg_deps
  # get CppAD:
  # - git clone https://github.com/coin-or/CppAD.git cppad
  # - cd cppad
  - CPPAD_VERSION_NAME=20200000.2
  - wget https://github.com/coin-or/CppAD/archive/${CPPAD_VERSION_NAME}.tar.gz
  - tar -xzf ${CPPAD_VERSION_NAME}.tar.gz
  - cd CppAD-${CPPAD_VERSION_NAME}
  - mkdir build
  - mkdir install
  - CPPAD_HOME=`pwd`/install/include
  - echo $CPPAD_HOME
  - cd build
  - cmake -Dcppad_prefix:PATH=../install -Dcppad_cxx_flags="-Wall -std=c++11 -Wshadow" ..
  - make install
  - cd ../..
  # get Eigen:
  - wget http://bitbucket.org/eigen/eigen/get/3.3.7.tar.bz2
  - tar -jxf 3.3.7.tar.bz2
  - cd eigen-eigen-323c052e1731
  - mkdir -p install_eigen/include/eigen3
  - cp -r Eigen ./install_eigen/include/eigen3/
  - EIGEN_HOME=`pwd`/install_eigen/include/eigen3
  - echo $EIGEN_HOME
  #
  - cd ../..

script:
  - mkdir build
  - cd build
  - cmake -DCMAKE_BUILD_TYPE=DEBUG -DGOOGLETEST_GIT=ON -DUSE_VALGRIND=OFF -DENABLE_THREAD_POOL_TESTS=OFF -DLLVM_VERSION=3.6 -DCPPAD_HOME=$CPPAD_HOME -DEIGEN3_INCLUDE_DIR=$EIGEN_HOME ..
  - cd test
  - make -j2 build_tests
  - CTEST_OUTPUT_ON_FAILURE=TRUE make test
